### ISSUE TITLE
blog.kalon.ro reskin

### ISSUE THREAD

**Issue by andrigherghe** [Kalon/blog#8]
@andrigherghe commented on [Tue Feb 16 2016](https://github.com/Kalon/kalon.ro/issues/64)

http://blog.kalon.ro/ - needs reskin, acording to the new website design. Extended case studies will go here as dedicated posts. 

## ToDo:

- [ ] **Change blog logo from logotype with "Kalon"**

![image](https://cloud.githubusercontent.com/assets/15648055/13071032/7525a038-d499-11e5-8366-81f7a179ca58.png)

- [ ] **Replace header image:**

![image](https://cloud.githubusercontent.com/assets/15648055/13071059/9bd1ec14-d499-11e5-8834-39eca78af1c0.png)

- [ ] **Replace / hide big blog logo* & round placeholder:**
![image](https://cloud.githubusercontent.com/assets/15648055/13071102/eae45c9c-d499-11e5-892e-62627859715b.png)

* It's the same image source as the one from small blog logo ( 
![image](https://cloud.githubusercontent.com/assets/15648055/13071144/2f3d6cc6-d49a-11e5-8a4d-c87bac2ee4b5.png) ) 

- [ ] **Replace post footer:**

![image](https://cloud.githubusercontent.com/assets/15648055/13071020/5dfe239e-d499-11e5-9cd4-8d8412367e56.png)

---

@andrigherghe commented on [Wed Feb 24 2016](https://github.com/Kalon/kalon.ro/issues/64#issuecomment-188272159)

@nicubalan , after you're done with the website design, please work on this task. 10x!

---

@valentintureac commented on [Thu Feb 25 2016](https://github.com/Kalon/kalon.ro/issues/64#issuecomment-188667121)

There's a repo for that project. https://github.com/Kalon/blog

Let's keep them separate, please.

**Comment by andrigherghe** [comment]
@nicubalan , task moved here. when can you start working on it? Thanks!
Andri

**Comment by nicubalan** [comment]
@andrigherghe I'll try start working on it tomorrow, after I'll finish the tablet and review once again the web pages.

**Comment by andrigherghe** [comment]
Thanks! Let me know if you have any questions and if I can help with anything, or just when we can review it together.
